# Generated by Django 5.0.1 on 2024-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_list',
            name='Data',
            field=models.DateField(blank=True),
        ),
    ]
